# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: 
  en: "Evlaa Blog"
  fr: "Evlaa le Blog"
description: #>  this means to ignore newlines until "email:"
  en: We will share Tips to help photographers improve their digital skills
  fr: Nous partageons ici des Tips pour aider les photographes à améliorer leur présence digitale
copyright:  
  en: All content copyright 
  fr: Tout contenu est la propriété de
reserved: 
  en: All rights reserved.
  fr: Tous les droits sont réservés.
love: 
  en: Made with 
  fr: Fait avec
and: 
  en: and
  fr: et 
backoverview: 
  en: Back to Overview
  fr: Retour à l'accueil

email: evlaa@evlaa.com
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Evlaa'
author: 'Martin Letellier'
author_image: "/assets/images/martin.jpg"

paginate:	5
future: true

url: "https://blog.evlaa.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@evlaaPlugin'

#fill in disqus shortname to use disqus
disqus: evlaa

# social icons and sharing options
social:
  - icon:	facebook
    url:	https://facebook.com/evlaa
    desc: Follow us on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: twitter
    url:  https://twitter.com/evlaaPlugin
    desc: Follow us on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: google-plus
    desc:  Add me on google
    share_url: https://plus.google.com/share
    share_title: ?text=
    share_link: "&amp;url="
  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:


